### PR TITLE
Add unknown trigger types

### PR DESCRIPTION
**Pull request by JeremyAnsel**

### CODE REVIEW

**Comment by MikeG621** [comment]
Trigger type 22: in Mission.Trigger you've defined it as "Not player of GG", but in Strings it's "All player of GGs except" which could imply a GG or player number.  Since this should be a GG, I think a better phrasing in Strings is "All players except in GG", if that matches your intent.

**Comment by JeremyAnsel** [comment]
The variable value is a player number.

**Comment by MikeG621** [comment]
One last question; For the delay, case 14: is that in straight seconds, or is there a multiplier on it?  Back before there were separate Minute/Second delays for ArrDep, the delay was multiplied by 5s.

**Comment by JeremyAnsel** [comment]
The delay is multiplied by 5s.

**Comment by MikeG621** [comment]
Do you know of any stock implementations of the Type 14 delay?  I've been trying to scan for it with a tool I built ages ago but it's clunky and I keep coming up empty.  Since the TriggerType enum is used in not only all Triggers in FGs, Messages and GlobalGoals, but also the Order's TargetType, that's easily thousands of locations per mission and the Load routine doesn't lend itself to hacking in a spy, either.

Trying to see how it interacts with the trigger since is doesn't really follow the rest of the patterns. "100% of After 5s Delay must (TRUE)" doesn't make sense unless it's linked to something else.

If you don't that's fine, it's just going to take me a while to hack something in to look for it.

**Comment by JeremyAnsel** [comment]
The code that checks the delay trigger type looks like that:
```c++
    case TieClass_AfterDelay:
    {
        int ecx = targetParameter * 5;

        short si = ecx / 60;
        short dx = ecx % 60;

        if( si < s_V0x08053E0.TimeMinutes )
            return false;

        if( si > s_V0x08053E0.TimeMinutes )
            return true;

        return dx >= s_V0x08053E0.TimeSeconds ? true : false;
    }
```

**Comment by MikeG621** [comment]
Okay, so it ignores everything else within the trigger.  Follow up then
would be what's s_V0x08053E0 a reference to?  Is that the overall mission
timer?

--
Michael Gaisser
850-396-4535

**Comment by JeremyAnsel** [comment]
`s_V0x08053E0` is a structure that holds various variables about the current mission. Its size is 11570.

**Comment by MikeG621** [comment]
Merged

**Pull request closed without merging**
